{{if .Values.ezua.selfSignedCert }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: clone-and-sync-ingress-cert-to-{{ .Release.Namespace }}-namespace
spec:
  background: false
  generateExisting: true
  rules:
  - generate:
      apiVersion: v1
      clone:
        name: ingress-cert
        namespace: istio-system
      kind: Secret
      name: platform-ingress-cert
      namespace: {{ .Release.Namespace }}
      synchronize: true
    match:
      resources:
        kinds:
        - Namespace
        names:
        - {{ .Release.Namespace }}
    name: sync-platform-ingress-cert-secret
  validationFailureAction: Audit
{{ end }}
